# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins
#
# Please find additional hints for individual trigger use case
# configuration options inline this script below.
#
---
name: cd
on:
  workflow_dispatch:
    inputs:
      validate_only:
        required: false
        type: boolean
        description: |
          Run validation with release drafter only
          → Skip the release job
        # Note: Change this default to true,
        #       if the checkbox should be checked by default.
        default: false
  # Trigger automatically on pushes to main (when PRs are merged)
  # Note: push trigger is used because check_run events from workflows
  # in the same repository don't trigger other workflows, and workflow_run
  # is not yet supported by verify-ci-status-action
  push:
    branches:
      - main

permissions:
  checks: read
  contents: write

jobs:
  # Verify Jenkins CI completed successfully before running CD
  check-ci:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      ci-passed: ${{ steps.check.outputs.passed }}
    steps:
      - name: Check Jenkins CI status
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Query the Jenkins check run status for this commit
          CHECK_CONCLUSION=$(gh api -X GET \
            -F check_name="Jenkins" \
            -F status=completed \
            "/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs" \
            | jq -r '.check_runs[0].conclusion // "pending"')
          
          echo "Jenkins check conclusion: $CHECK_CONCLUSION"
          
          if [ "$CHECK_CONCLUSION" = "success" ]; then
            echo "passed=true" >> $GITHUB_OUTPUT
            echo "✅ Jenkins CI passed"
          else
            echo "passed=false" >> $GITHUB_OUTPUT
            echo "❌ Jenkins CI did not pass (status: $CHECK_CONCLUSION)"
            exit 1
          fi

  maven-cd:
    needs: [check-ci]
    if: always() && (needs.check-ci.result == 'success' || needs.check-ci.result == 'skipped')
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    with:
      # Comment / uncomment the validate_only config appropriate to your preference:
      #
      # Use case #1 (automatic release):
      #   - Let any successful Jenkins build trigger another release,
      #     if there are merged pull requests of interest
      #   - Perform a validation only run with drafting a release note,
      #     if manually triggered AND inputs.validate_only has been checked.
      #
      validate_only: ${{ inputs.validate_only == true }}
      #
      # Alternative use case #2 (no automatic release):
      #   - Same as use case #1 - but:
      #     - Let any check_run trigger a validate_only run.
      #       => enforce the release job to be skipped.
      #
      #validate_only: ${{ inputs.validate_only == true || github.event_name == 'check_run' }}
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
